
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# Set your monitor configuration here
# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-3, 2560x1440@120, 0x0, 1.25
monitor=DP-1, preferred, auto-right, 1
monitor=DP-2, preferred, auto-left, 1, transform, 1

# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

# See https://wiki.hyprland.org/Configuring/Master-Layout/

# Workspace bindings and rules:
workspace=1, monitor:DP-3, persistent:true, default:true
workspace=2, monitor:DP-2, persistent:true, default:true
workspace=3, monitor:DP-1, persistent:true, default:true

